version: "3.7"

services:

  reactclient:
    build: ./reactclient
    container_name: reactclient
    restart: always
    # environment:
    expose:
      - 5000
    depends_on:
      - mssqldb
      - kestrelwebserver

  kestrelwebserver:
    build: ./kestrelwebserver
    container_name: kestrelwebserver
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ClientId=
      # - ClientSecret
      # - DefaultConnection=
    expose:
      - 3001
    depends_on:
      - mssqldb

  nginxwebserver:
    build: ./nginxwebserver
    container_name: nginxwebserver
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mssqldb
      - kestrelwebserver
      - reactclient
    
  mssqldb:
    build: ./mssqldb
    container_name: mssqldb
    restart: always
    # environment
      # - SA_PASSWORD=<your_strong_password>
      ACCEPT_EULA: "Y"
    expose: 
      - 4000
    # volumes
      # - ./topicsdb

